### ISSUE TITLE
Numpy and Cython are not automatically installed at `pip install`

### ISSUE THREAD

**Issue by NomotoEriko** [cocodataset/cocoapi#288]
Hi, 

It seems that `setup.py` dependents on `numpy` and `cython` but these are not installed automatically when I run `pip install pycocotools`.

If you add `pyproject.toml` and below to the `pycocotools-2.0.0.tar.gz` source, these dependencies will be automatically installed.
```toml:pyproject.toml
[build-system]
requires=['setuptools', 'wheel', 'numpy', 'cython>=0.27.3']
```
Because the module dependents on `matplotlib`, `setup.cfg` below will be required.
```cfg:setup.cfg
[options]
install_requires = 
  matplotlib>=2.1.0
```
_____
If you upgrade `setup.py` to the latest version, `pyproject.toml` below would work without `setup.cfg`.
```toml:pyproject.toml
[build-system]
requires=['setuptools', 'wheel', 'numpy']
```
